buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath("org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:${kotlinVersion}")
  }
}

apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

group = 'com.versutus.widget'
version = '0.1.0'

android {
  namespace "com.versutus.widget"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  buildFeatures {
    compose true
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'androidx.glance:glance-appwidget:1.2.0'
  implementation 'androidx.glance:glance-material3:1.2.0'
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.json:json:20240303'
}
